config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, except: [:destroy, :edit, :update] do
    resources :reviews, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  valid_categories = ["chinese", "italian", "japanese", "french", "belgian"]
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :phone_number, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: valid_categories }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true}, inclusion: { in: [0, 1, 2, 3, 4, 5]}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.valid?
      @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = Review.new(reviews_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    return redirect_to restaurant_path(@restaurant) if @review.save
    render :new
  end

  private

  def reviews_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsYelpMvp</title>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  </html>

app/views/restaurants/_form.html.erb
<h1><%= @restaurant.name%></h1>

<%= form_for @restaurant do |f| %>
  <%= f.label :restaurant, "restaurant"%>
  <%= f.text_field :name %>
  <%= f.label :address, "address"%>
  <%= f.text_field :address %>
  <%= f.label :phone_number, "phone number"%>
  <%= f.text_field :phone_number %>
  <%= f.label :category, "category"%>
  <%= f.select :category, ["chinese", "italian", "japanese", "french", "belgian"] %>
  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>



<%= link_to "add", new_restaurant_path, method: :index, data: {confirm: "Are you sure you to add this restaurant?"} %>



<ul>
  <% @restaurants.each do |restaurant| %>
  <li>
    <%= link_to restaurant.name, restaurant_path(restaurant) %> -

  </li>
  <%end %>
</ul>

app/views/restaurants/new.html.erb
<h1><%= @restaurant.name %></h1>

<%= render "form" %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name%> </h1>


  <%= @restaurant.name  %>
  <%=  @restaurant.address%>
  <%=  @restaurant.phone_number%>
  <%=  @restaurant.category%>

<h1>Reviews</h1>

<% @reviews.each do |review| %>
  <li><%= review.content %> (<%= review.rating %>)</li>
<% end %>

<%= link_to "Add a new review", new_restaurant_review_path(@restaurant)  %>


<%= link_to "go home", restaurants_path %>

app/views/reviews/_form.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :content, "content"%>
  <%= f.text_field :content %>
  <%= f.label :rating, "rating"%>
  <%= f.text_field :rating %>
<%= f.submit %>
<% end %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<%= link_to "add", new_review_path, method: :index, data: {confirm: "Are you sure you to add this review?"} %>

<ul>
  <% @reviews.each do |review| %>
  <li>
    <%= link_to review.restaurant, review_path(review) %> -
  </li>
  <%end %>
</ul>

app/views/reviews/new.html.erb
<h1>Add a new review</h1>

<%= render "form" %>

app/views/reviews/show.html.erb
<h1><%= @review.restaurant%> </h1>


  <%= @review.restaurant  %>
  <%=  @review.address%>
  <%=  @review.phone_number%>
    <%= link_to "go home", reviews_path %>